-- Shared project budgets survive ingest restarts and apply across replicas.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM getexception_mail;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM getexception_mail;
REVOKE ALL ON SCHEMA public FROM getexception_mail;

CREATE TABLE project_admission_bucket (
  "projectId" text PRIMARY KEY REFERENCES project(id) ON DELETE CASCADE,
  credit double precision NOT NULL CHECK (credit >= 0 AND credit <= 50),
  at timestamptz NOT NULL
);

CREATE OR REPLACE FUNCTION admit_inbox() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE quota integer; daily integer; installation integer; available double precision; admission_time timestamptz;
BEGIN
 NEW."receivedAt" := clock_timestamp();
 IF NEW."projectId" IS NULL THEN
   IF NEW."eventId" <> '00000000000000000000000000000000' OR NEW.payload <> '{}'::jsonb THEN
     RAISE EXCEPTION 'invalid_probe' USING ERRCODE = '23514';
   END IF;
   RETURN NEW;
 END IF;
 PERFORM 1 FROM admission_state WHERE id = 1 FOR UPDATE;
 IF EXISTS (SELECT 1 FROM event_inbox WHERE "projectId" = NEW."projectId" AND "eventId" = NEW."eventId") THEN RETURN NULL; END IF;
 SELECT "dailyQuota" INTO quota FROM project WHERE id = NEW."projectId" AND enabled AND "deletedAt" IS NULL;
 IF quota IS NULL OR NOT EXISTS (SELECT 1 FROM system_setting WHERE id = 1) THEN RAISE EXCEPTION 'ingest_disabled' USING ERRCODE = '23514'; END IF;
 UPDATE admission_state SET day = CURRENT_DATE, accepted = 0 WHERE id = 1 AND day <> CURRENT_DATE;
 SELECT accepted INTO installation FROM admission_state WHERE id = 1;
 SELECT accepted INTO daily FROM project_daily_stat WHERE "projectId" = NEW."projectId" AND day = CURRENT_DATE;
 IF installation >= 100000 OR coalesce(daily,0) >= quota OR (SELECT count(*) FROM event_inbox i JOIN project p ON p.id = i."projectId" WHERE i.status IN ('pending','processing') AND p."deletedAt" IS NULL) >= 10000 THEN
   RAISE EXCEPTION 'ingest_capacity' USING ERRCODE = '23514';
 END IF;
 admission_time := clock_timestamp();
 INSERT INTO project_admission_bucket("projectId", credit, at) VALUES (NEW."projectId", 50, admission_time) ON CONFLICT DO NOTHING;
 SELECT least(50, credit + greatest(0, extract(epoch FROM admission_time - at)) * 20) INTO available
 FROM project_admission_bucket WHERE "projectId" = NEW."projectId";
 IF available < 1 THEN RAISE EXCEPTION 'ingest_capacity' USING ERRCODE = '23514'; END IF;
 UPDATE project_admission_bucket SET credit = available - 1, at = admission_time WHERE "projectId" = NEW."projectId";
 UPDATE admission_state SET accepted = accepted + 1 WHERE id = 1;
 INSERT INTO project_daily_stat("projectId",day,accepted) VALUES (NEW."projectId",CURRENT_DATE,1)
 ON CONFLICT ("projectId",day) DO UPDATE SET accepted = project_daily_stat.accepted + 1;
 RETURN NEW;
END;
$$;

-- An admission exception rolls its transaction back. Record the rejection in a
-- separate bounded operation, without granting ingest access to statistics.
CREATE FUNCTION record_ingest_rejection(project_id text, key_hash text) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM ingestion_config WHERE "projectId" = project_id AND "keyHash" = key_hash) THEN RETURN; END IF;
 INSERT INTO project_daily_stat("projectId", day, accepted, rejected) VALUES (project_id, CURRENT_DATE, 0, 1)
 ON CONFLICT ("projectId",day) DO UPDATE SET rejected = least(project_daily_stat.rejected, 2147483646) + 1;
END;
$$;
REVOKE ALL ON FUNCTION record_ingest_rejection(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION record_ingest_rejection(text, text) TO getexception_ingest;

-- Operator-only cleanup of the exact event generated by deployment verification.
CREATE FUNCTION cleanup_deployment_probe(project_id text, event_id text) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE target_id text; issue_id text; received_day date;
BEGIN
 PERFORM 1 FROM admission_state WHERE id = 1 FOR UPDATE;
 SELECT id, "issueId", ("receivedAt" AT TIME ZONE 'UTC')::date INTO target_id, issue_id, received_day
 FROM error_event WHERE "projectId" = project_id AND "eventId" = event_id
   AND "exceptionType" = 'DeploymentProbe' AND message = 'GetException deployment probe' FOR UPDATE;
 IF target_id IS NULL THEN RETURN false; END IF;
 DELETE FROM error_event WHERE id = target_id;
 DELETE FROM event_inbox WHERE "projectId" = project_id AND "eventId" = event_id;
 UPDATE issue SET "eventCount" = greatest(0, "eventCount" - 1) WHERE id = issue_id;
 DELETE FROM issue WHERE id = issue_id AND "eventCount" = 0 AND NOT EXISTS (SELECT 1 FROM error_event WHERE "issueId" = issue_id);
 UPDATE project_daily_stat SET accepted = greatest(0, accepted - 1) WHERE "projectId" = project_id AND day = received_day;
 DELETE FROM project_daily_stat WHERE "projectId" = project_id AND day = received_day AND accepted = 0 AND rejected = 0;
 UPDATE admission_state SET accepted = greatest(0, accepted - 1) WHERE id = 1 AND day = received_day;
 RETURN true;
END;
$$;
REVOKE ALL ON FUNCTION cleanup_deployment_probe(text, text) FROM PUBLIC;

CREATE OR REPLACE VIEW runtime_schema AS SELECT 10 AS version
 WHERE (SELECT count(*) FROM _prisma_migrations WHERE finished_at IS NOT NULL AND rolled_back_at IS NULL) = 11
 AND NOT EXISTS (SELECT 1 FROM _prisma_migrations WHERE finished_at IS NULL AND rolled_back_at IS NULL);
