export const actions: Record<string, string> = {
  setup_access: "Setup access",
  setup_prepare: "Authenticator setup",
  setup_activate: "Installation activated",
  password: "Password verification",
  totp: "Authenticator verification",
  recovery: "Recovery code used",
  step_up: "Identity confirmation",
  project_create: "Project created",
  issue_resolve: "Issue resolved",
  issue_reopen: "Issue reopened",
  team_create: "Team created",
  team_update: "Team updated",
  member_update: "Member access updated",
  invitation_create: "Invitation created",
  invitation_resend: "Invitation resent",
  invitation_revoke: "Invitation revoked",
  invitation_accept: "Invitation accepted",
  mfa_enable: "Authenticator enabled",
  mfa_disable: "Authenticator disabled",
};
